server:
  port: 9919
spring:
  application:
    name: products-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver