server:
  port: 9919
spring:
  application:
    name: products-service
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:9091 }
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
